

============================== 2023-09-23 03:13:12.706952 | 61693c27-7503-427e-a76d-fe25f8b13692 ==============================
[0m03:13:12.706952 [info ] [MainThread]: Running with dbt=1.4.6
[0m03:13:12.707814 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '/Users/kolawole/.dbt', 'send_anonymous_usage_stats': True, 'quiet': False, 'no_print': False, 'cache_selected_only': False, 'skip_profile_setup': False, 'which': 'init', 'indirect_selection': 'eager'}
[0m03:13:12.707945 [debug] [MainThread]: Tracking: tracking
[0m03:13:12.721793 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcba3da940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcba3a1d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcba3b8ee0>]}
[0m03:13:39.149617 [debug] [MainThread]: Starter project path: /Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/include/starter_project
[0m23:50:46.105654 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11063eb00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11428e320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11428ea40>]}


============================== 23:50:46.108233 | fca916d1-f0b0-4fd1-9bfb-11b3153070b1 ==============================
[0m23:50:46.108233 [info ] [MainThread]: Running with dbt=1.6.3
[0m23:50:46.108696 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/kolawole/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:50:46.109034 [info ] [MainThread]: dbt version: 1.6.3
[0m23:50:46.109204 [info ] [MainThread]: python version: 3.10.4
[0m23:50:46.109368 [info ] [MainThread]: python path: /Users/kolawole/.local/share/virtualenvs/transformation_with_dbt-31lOpkgf/bin/python
[0m23:50:46.109533 [info ] [MainThread]: os info: macOS-13.6-arm64-arm-64bit
[0m23:50:46.261886 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.bigquery'
[0m23:50:46.265430 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.postgres'
[0m23:50:46.267046 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.postgres'
[0m23:50:46.268418 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.postgres'
[0m23:50:46.270434 [info ] [MainThread]: Using profiles dir at /Users/kolawole/.dbt
[0m23:50:46.270766 [info ] [MainThread]: Using profiles.yml file at /Users/kolawole/.dbt/profiles.yml
[0m23:50:46.270971 [info ] [MainThread]: Using dbt_project.yml file at /Users/kolawole/Documents/PersonalProjects/transformation-with-dbt/dbt_project.yml
[0m23:50:46.271201 [info ] [MainThread]: Configuration:
[0m23:50:46.271369 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m23:50:46.271588 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m23:50:46.271914 [info ] [MainThread]: Required dependencies:
[0m23:50:46.272163 [debug] [MainThread]: Executing "git --help"
[0m23:50:46.287826 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m23:50:46.288645 [debug] [MainThread]: STDERR: "b''"
[0m23:50:46.288906 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m23:50:46.289245 [info ] [MainThread]: Connection test skipped since no profile was found
[0m23:50:46.289552 [info ] [MainThread]: [31m2 checks failed:[0m
[0m23:50:46.289751 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "adw", target "dev" invalid: Runtime Error
    Could not find adapter type bigquery!

Runtime Error
  Credentials in profile "corise_adv_sql", target "dev" invalid: ['anything'] is not valid under any of the given schemas

Runtime Error
  Credentials in profile "feld_m_analytics_engineer", target "dev" invalid: Runtime Error
    Could not find adapter type postgres!

Runtime Error
  Credentials in profile "feld_m_rework", target "dev" invalid: Runtime Error
    Could not find adapter type postgres!

Runtime Error
  Credentials in profile "mendeley_warehouse", target "dev" invalid: Runtime Error
    Could not find adapter type postgres!


[0m23:50:46.289947 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/kolawole/Documents/PersonalProjects/transformation-with-dbt/dbt_project.yml> not found

[0m23:50:46.290503 [debug] [MainThread]: Command `dbt debug` failed at 23:50:46.290423 after 0.20 seconds
[0m23:50:46.290832 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11063eb00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11428ebf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114b96530>]}
[0m23:50:46.291164 [debug] [MainThread]: Flushing usage events


============================== 2023-09-23 05:33:24.437046 | 9aa4f2a1-4abd-434c-a3e2-45a706618c99 ==============================
[0m05:33:24.437046 [info ] [MainThread]: Running with dbt=1.4.6
[0m05:33:24.438028 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '/Users/kolawole/.dbt', 'send_anonymous_usage_stats': True, 'quiet': False, 'no_print': False, 'cache_selected_only': False, 'config_dir': False, 'which': 'debug', 'indirect_selection': 'eager'}
[0m05:33:24.438151 [debug] [MainThread]: Tracking: tracking
[0m05:33:24.453530 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7b32080520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7b32121040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7b320ff8e0>]}
[0m05:33:26.434407 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7b321219a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7b33c34730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7b33c34160>]}
[0m05:33:26.434700 [debug] [MainThread]: Flushing usage events
[0m05:33:26.897573 [error] [MainThread]: Encountered an error:
cannot import name 'FailedToConnectException' from 'dbt.exceptions' (/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/exceptions.py)
[0m05:33:26.903216 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/main.py", line 136, in main
    results, succeeded = handle_and_check(args)
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/main.py", line 206, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/main.py", line 253, in run_from_args
    results = task.run()
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/task/debug.py", line 109, in run
    self.test_configuration()
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/task/debug.py", line 281, in test_configuration
    profile_status = self._load_profile()
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/task/debug.py", line 252, in _load_profile
    profile: Profile = Profile.render_from_args(self.args, renderer, profile_name)
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/config/profile.py", line 428, in render_from_args
    return cls.from_raw_profiles(
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/config/profile.py", line 394, in from_raw_profiles
    return cls.from_raw_profile_info(
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/config/profile.py", line 348, in from_raw_profile_info
    credentials: Credentials = cls._credentials_from_profile(
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/config/profile.py", line 181, in _credentials_from_profile
    cls = load_plugin(typename)
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/adapters/factory.py", line 202, in load_plugin
    return FACTORY.load_plugin(name)
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/adapters/factory.py", line 57, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/adapters/bigquery/__init__.py", line 1, in <module>
    from dbt.adapters.bigquery.connections import BigQueryConnectionManager  # noqa
  File "/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 26, in <module>
    from dbt.exceptions import (
ImportError: cannot import name 'FailedToConnectException' from 'dbt.exceptions' (/Users/kolawole/opt/anaconda3/lib/python3.8/site-packages/dbt/exceptions.py)

[0m01:02:45.334073 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a2c5d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a3c750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a3d310>]}


============================== 01:02:45.336896 | 7a07f745-660e-415b-9b5a-23471edd3542 ==============================
[0m01:02:45.336896 [info ] [MainThread]: Running with dbt=1.6.3
[0m01:02:45.337235 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/kolawole/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:02:45.337549 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/kolawole/Documents/PersonalProjects/transformation-with-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:02:45.337892 [debug] [MainThread]: Command `dbt run` failed at 01:02:45.337830 after 0.02 seconds
[0m01:02:45.338101 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a213d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a3d190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a3cf90>]}
[0m01:02:45.338299 [debug] [MainThread]: Flushing usage events
